---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Configure Firewall Rules 
# Requirements: 
#

- name: SET SYSCTL TO ALLOW EXTERNAL ROUTING
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
    state: present

- name: LOAD IPTABLES MASQUAREDE HTTPS RULE
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    protocol: tcp
    destination_port: 443
    jump: MASQUERADE

- name: LOAD IPTABLES PROXY TRANSPARENT RULE
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ppp0
    source: 10.0.0.0/24
    protocol: tcp
    destination_port: 80
    to_ports: 15379
    jump: REDIRECT

- name: SET SYSCTL TO ALLOW LOCAL ROUTING
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    reload: yes
    state: present

- name: LOAD IPTABLES DNAT PORT 8080
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ppp0
    protocol: tcp
    destination_port: 8080
    jump: DNAT
    to_destination: 127.0.0.1:15379

- name: LOAD IPTABLES DNAT PORT 53 TCP 
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ppp0
    protocol: tcp
    destination_port: 53 
    jump: DNAT
    to_destination: 127.0.0.1:53

- name: LOAD IPTABLES DNAT PORT 53 UDP 
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ppp0
    protocol: udp
    destination_port: 53 
    jump: DNAT
    to_destination: 127.0.0.1:53
