---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Install and start multitor project 
# Requirements: 
#

- name: GIT CLONE MULTITOR SOURCE PROJECT
  git:
    repo: 'https://github.com/trimstray/multitor.git'
    dest: /opt/multitor
    force: yes

- name: EXECUTE SETUP MULTITOR SCRIPT
  command: /opt/multitor/setup.sh install

- name: START MULTITOR
  shell: multitor --init 5 -u debian-tor --socks-port 9000 --control-port 9900 --proxy privoxy
