---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Install and configure pptpd server 
# Requirements: 
#

- name: CONFIGURE PPTPD LOCALIP
  lineinfile:
    path: /etc/pptpd.conf
    line: 'localip 10.0.0.1'

- name: CONFIGURE PPTPD REMOTEIP
  lineinfile:
    path: /etc/pptpd.conf
    line: 'remoteip 10.0.0.100-200'

- name: CONFIGURE PPTP USER
  lineinfile:
    path: /etc/ppp/chap-secrets
    line: "{{ torcity_user }} pptpd {{ torcity_pass }} *"

- name: CONFIGURE PPTP USER
  lineinfile:
    path: /etc/ppp/pptpd-options
    line: 'ms-dns 10.0.0.1'

- name: RESTART PPTPD SERVER
  service:
    name: pptpd
    state: restarted
    enabled: true
