---
- debug: msg="current host expected value:{{ groups['primary'][0] }} - current host current value:{{ inventory_hostname }}"

- name: copy createAdmin script
  template: src=createAdmins.j2 dest=/tmp/createAdmins.js

- name: create administrator users
  shell: mongo --ssl --sslAllowInvalidCertificates < /tmp/createAdmins.js
