---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Setup TOR DNS server 
# Requirements: 
#

- name: COPY TOR-DNS CONFIG SERVER
  copy:
    src: tor/torrc
    dest: /etc/tor/torrc

- name: LOAD IPTABLES DNAT UDP DNS PORT 
  iptables:
    table: nat
    chain: PREROUTING
    protocol: udp 
    destination_port: 53
    jump: DNAT
    to_destination: 127.0.0.1:53

- name: LOAD IPTABLES DNAT TCP DNS PORT
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 53
    jump: DNAT
    to_destination: 127.0.0.1:53

- name: RESTART TOR-DNS SERVER
  service:
    name: tor 
    state: restarted
    enabled: true
