---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: setup fail2ban
# Requirements: 
#

- name: CONFIGURE FILTER OF FAIL2BAN
  copy:
    src: fail2ban/filter.torcity-demo.conf
    dest: /etc/fail2ban/filter.d/torcity-demo.conf

- name: CONFIGURE ACTION ON FAIL2BAN
  copy:
    src: fail2ban/action.iptables.conf
    dest: /etc/fail2ban/action.d/iptables-multiport.conf

- name: CONFIGURE JAIL OF FAIL2BAN
  template:
    src: fail2ban/jail.conf.j2
    dest: /etc/fail2ban/jail.conf

- name: RESTART FAIL2BAN
  service:
    name: fail2ban
    state: restarted
    enabled: true

- name: CREATE ALIAS UNBAN COMMDAND
  shell: echo "alias torcity-demo-unban='fail2ban-client set torcity-demo unbanip '" >> ~/.bash_aliases
