---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: install/setup torcity-demo and dependencies 
# Requirements: 
#

- name: INSTALL DEPENDENCIES 
  include_tasks: dependencies.yml

- name: INSTALL/SETUP MULTITOR
  include_tasks: multitor.yml

- name: SETUP FAIL2BAN
  include_tasks: fail2ban.yml

- name: SETUP NGINX
  include_tasks: nginx.yml
