---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Install multitor project 
# Requirements: 
#

- name: GIT CLONE MULTITOR SOURCE PROJECT
  git:
    repo: 'https://github.com/trimstray/multitor.git'
    dest: /opt/multitor
    force: yes

- name: EXECUTE SETUP MULTITOR SCRIPT
  command: /opt/multitor/setup.sh install

- name: SET SYSCTL TO ALLOW LOCAL ROUTING
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    reload: yes
    state: present

- name: FIX MULTITOR LIB DIR
  file:
    state: directory
    path: /var/lib/multitor
    owner: debian-tor
    group: debian-tor

- name: STOP MULTITOR
  shell: multitor -k

- name: START MULTITOR
  shell: multitor --init {{ tor_servers }} -u debian-tor --socks-port 9000 --control-port 9900 --proxy privoxy

- name: COPY PRIVOXY CONFIG SERVER
  copy:
    src: multitor/privoxy.cfg
    dest: /opt/multitor/etc/privoxy.cfg

- name: COPY PRIVOXY USER ACTION 
  copy:
    src: multitor/user.action
    dest: /opt/multitor/etc/user.action

- name: RESTART PRIVOXY
  shell: |
    kill `ps auxw  | grep -i privoxy | awk '{ print $2 }' | head -n1`
    privoxy /opt/multitor/bin/../etc/privoxy.cfg

#- name: LOAD IPTABLES DNAT PORT 8080
#  iptables:
#    table: nat
#    chain: PREROUTING
#    protocol: tcp
#    destination_port: 8080
#    jump: DNAT
#    to_destination: 127.0.0.1:15379
