---
# Author: Vagner Rodrigues Fernandes <vagner.rodrigues@gmail.com>
# Description: Install multitor project 
# Requirements: 
#

- name: GIT CLONE MULTITOR SOURCE PROJECT
  git:
    repo: 'https://github.com/trimstray/multitor.git'
    dest: /opt/multitor
    force: yes

- name: EXECUTE SETUP MULTITOR SCRIPT
  command: /opt/multitor/setup.sh install

- name: COPY PRIVOXY TEMPLATE SERVER
  copy:
    src: privoxy-template.cfg
    dest: /opt/multitor/templates/privoxy-template.cfg

- name: SET SYSCTL TO ALLOW LOCAL ROUTING
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    reload: yes
    state: present

- name: LOAD IPTABLES DNAT PORT 8080
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 8080
    jump: DNAT
    to_destination: 127.0.0.1:15379

- name: CONFIGURE FILTER OF FAIL2BAN
  copy:
    src: fail2ban.filter.torcity-demo
    dest: /etc/fail2ban/filter.d/torcity-demo.conf

- name: CONFIGURE ACTION ON FAIL2BAN
  copy:
    src: fail2ban.action.iptables.conf
    dest: /etc/fail2ban/action.d/iptables-multiport.conf

- name: CONFIGURE JAIL OF FAIL2BAN
  copy:
    src: fail2ban.jail.conf
    dest: /etc/fail2ban/jail.conf

- name: RESTART FAIL2BAN
  service:
    name: fail2ban
    state: restarted
    enabled: true

- name: CONFIGURE BAN PAGE
  copy:
    src: nginx.default.conf
    dest: /etc/nginx/sites-enabled/default

- name: CONFIGURE BAN PAGE
  copy:
    src: nginx.index.html
    dest: /var/www/html/index.html

- name: RESTART NGINX 
  service:
    name: nginx
    state: restarted
    enabled: true
